# Equirectangular model for RICOH THETA S

#==============#
# Camera Model #
#==============#

Camera.name: "S3C"
Camera.setup: "monocular"
Camera.model: "perspective"

Camera.fps: 30.0
Camera.cols: 1920
Camera.rows: 1080

Camera.fx: 907.491014
Camera.fy: 911.998511
Camera.cx: 920.941178
Camera.cy: 543.722086

# Undistortion Process will be done out of OpenVSLAM
Camera.k1: 0.0000000
Camera.k2: 0.0000000
Camera.p1: 0.0000000
Camera.p2: 0.0000000
Camera.k3: 0.0000000

Camera.color_order: "RGB"

#================#
# ORB Parameters #
#================#

Feature.max_num_keypoints: 2000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7
